apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mongoose
  namespace:
  labels:
    type: statefulset
spec:
  serviceName: mongoose
  replicas: 3
  selector:
    matchLabels:
      app: mongoose
  template:
    metadata:
      labels:
        app: mongoose
    spec:
      subdomain: mongoose
      containers:
      - name: mongoose
        image: rslota/mongooseim-kube:latest
        env:
          - name: MASTER_ORDINAL
            value: "0"
          - name: NODE_TYPE
            value: "name"
        ports:
        - name: epmd
          containerPort: 4369
        - name: c2s
          containerPort: 5222
        - name: s2s
          containerPort: 5269
        - name: bosh
          containerPort: 5280
        - name: erlang-dist
          containerPort: 9100
        volumeMounts:
        - name: config-map
          mountPath: /member
        # - name: mnesia
        #   mountPath: /var/lib/mongooseim
      volumes:
        - name: config-map
          configMap:
            name: mongooseim
  # volumeClaimTemplates:
  # - metadata:
  #     name: mnesia
  #     annotations:
  #       volume.beta.kubernetes.io/storage-class: "dynamic-nfs"
  #   spec:
  #     accessModes:
  #       - ReadWriteMany
  #     resources:
  #       requests:
  #         storage: 10Mi
  #     storageClassName: dynamic-nfs

